### ISSUE TITLE
Where can I find actual images?

### ISSUE THREAD

**Issue by alikhil** [confluentinc/schema-registry-images#35]
I am looking for docker image for v6.2.0-305 but there is no such in [docker hub](https://hub.docker.com/r/confluentinc/cp-schema-registry/tags?page=1&ordering=last_updated)

**Comment by andrewegel** [comment]
CP 6.2.0 has not been released yet at this time. When it is, you'll see appropriate tags on Docker Hub. The current latest should be 6.1.1.
