### ISSUE TITLE
Remove Python Libraries

### ISSUE THREAD

**Issue by skhraashid** [confluentinc/schema-registry-images#43]
Hi, Is there any way we can remove python depency from this docker image, I am only using Java, and the install python libraries has many critical security vulanerablities. 

Thanks.

**Comment by andrewegel** [comment]
> Is there any way we can remove python depency from this docker image

Not without breaking other users that use this functionality of passing environment variables and translating them into Java config properties files. So your really only option is to build your own image with the software that you need.

This aspect may be revisited at future point in time to use things like `docker config` and `docker secret` features, but there's nothing on the roadmap around this.

> python libraries has many critical security vulanerablities.

We scan our latest docker image releases for _vulnerabilities_ and address them in quarterly release. Provided that you're using the latest images for your major version line these _vulnerabilities_ should be addressed.
