### ISSUE TITLE
Missing Version 5.5.7 on Docker Hub

### ISSUE THREAD

**Issue by tcoffin** [confluentinc/schema-registry-images#51]
The release for 5.5.7 was generated on December 8th, however the tag for 5.5.7 is not present on Docker Hub. 
Other releases, such as 6.2.2 (generated December 9th) are present on Docker Hub.

Please post 5.5.7 to Docker Hub, or advise if there's a preferred primary registry for Confluent Images.

**Comment by andrewegel** [comment]
These will be pushed to the docker-hub by the end of the week.
